services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Rmsstuttgart\RmsAiSearch\:
        resource: '../Classes/**'
        exclude:
            - '../Classes/Domain/Model/*'
